USE DATABASE IDENTIFIER($TARGET_DB);
USE SCHEMA AGENT_FRAMEWORK;

CREATE STAGE IF NOT EXISTS AGENT_FRAMEWORK.DCM_OUTPUT
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Output stage for generated DCM project files';

CREATE OR REPLACE PROCEDURE AGENT_FRAMEWORK.GENERATE_DCM_PROJECT(
    project_name      VARCHAR DEFAULT 'adf_pipeline',
    data_engineer_role VARCHAR DEFAULT 'DATA_ENGINEER_ROLE',
    analyst_role      VARCHAR DEFAULT 'ANALYST_ROLE'
)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'run'
EXECUTE AS OWNER
AS $$
import json, tempfile, os, textwrap

def run(session, project_name='adf_pipeline', data_engineer_role='DATA_ENGINEER_ROLE', analyst_role='ANALYST_ROLE'):
    db = session.sql("SELECT CURRENT_DATABASE()").collect()[0][0]

    # ── Silver tables — from lineage map (schema may be SILVER or AGENT_FRAMEWORK_OUTPUT) ──
    silver_rows = session.sql(
        f"SELECT SILVER_TABLE, SILVER_SCHEMA FROM {db}.AGENT_FRAMEWORK.TABLE_LINEAGE_MAP "
        f"WHERE silver_status = 'COMPLETE' AND SILVER_TABLE IS NOT NULL ORDER BY SILVER_TABLE"
    ).collect()
    silver_tables = [(r[1], r[0]) for r in silver_rows]  # [(schema, table), ...]

    # ── Gold tables — from lineage map ────────────────────────────────────────
    gold_rows = session.sql(
        f"SELECT GOLD_TABLE, GOLD_SCHEMA FROM {db}.AGENT_FRAMEWORK.TABLE_LINEAGE_MAP "
        f"WHERE gold_status = 'COMPLETE' AND GOLD_TABLE IS NOT NULL ORDER BY GOLD_TABLE"
    ).collect()
    gold_tables = [(r[1], r[0]) for r in gold_rows]  # [(schema, table), ...]

    # ── Planner strategies + PK columns ──────────────────────────────────────
    strat_rows = session.sql("""
        SELECT UPPER(SPLIT_PART(source_table, '.', -1)) AS tbl,
               transformation_strategy,
               detected_patterns,
               recommended_actions
        FROM AGENT_FRAMEWORK.PLANNER_DECISIONS pd
        JOIN AGENT_FRAMEWORK.WORKFLOW_EXECUTIONS we ON pd.execution_id = we.execution_id
        WHERE we.status IN ('COMPLETED', 'VALIDATED')
        QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(SPLIT_PART(source_table,'.',-1))
                                   ORDER BY we.started_at DESC) = 1
    """).collect()
    strategies = {r[0]: {'strategy': r[1], 'patterns': r[2]} for r in strat_rows}

    # Build PK map from Planner decisions — actions where reason mentions "primary key"
    pk_map = {}
    for r in strat_rows:
        tbl = r[0]
        try:
            actions = json.loads(r[3]) if r[3] else []
        except Exception:
            actions = []
        pks = [
            a['column'] for a in actions
            if isinstance(a, dict)
            and 'primary key' in a.get('reason', '').lower()
            and a.get('column')
        ]
        if pks:
            pk_map[tbl] = pks

    # ── Column metadata ───────────────────────────────────────────────────────
    def get_columns(schema, table):
        # schema may be 'DB.SCHEMA' (cross-db) or plain 'SCHEMA'
        parts = schema.split('.')
        info_db     = parts[0] if len(parts) > 1 else db
        schema_only = parts[-1]
        rows = session.sql(f"""
            SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH,
                   NUMERIC_PRECISION, NUMERIC_SCALE
            FROM {info_db}.INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = '{schema_only}' AND TABLE_NAME = '{table}'
            ORDER BY ORDINAL_POSITION
        """).collect()
        return rows

    def snowflake_type(row):
        dt = row[1].upper()
        if dt in ('TEXT', 'VARCHAR'):
            ml = row[4]
            return f'VARCHAR({ml})' if ml else 'VARCHAR'
        if dt == 'NUMBER':
            p, s = row[4], row[5]
            if p and s is not None:
                return f'NUMBER({p},{s})'
            return 'NUMBER'
        return dt

    def col_def(row):
        col   = row[0]
        dtype = snowflake_type(row)
        null  = '' if row[2] == 'YES' else ' NOT NULL'
        return f'    {col} {dtype}{null}'

    # ── manifest.yml ──────────────────────────────────────────────────────────
    manifest = f"""\
version: "1"
project_name: "{project_name}"
default_target: DEV
targets:
  DEV:
    project_identifier: "{db}.AGENT_FRAMEWORK.{project_name.upper()}"
    templating:
      env: dev
  PROD:
    project_identifier: "{db}.AGENT_FRAMEWORK.{project_name.upper()}"
    templating:
      env: prod
"""

    # ── infrastructure.sql ────────────────────────────────────────────────────
    silver_schemas = sorted(set(s for s, _ in silver_tables))
    gold_schemas   = sorted(set(s for s, _ in gold_tables))
    all_schemas    = sorted(set(silver_schemas + gold_schemas))
    schema_defs    = '\n'.join(f'DEFINE SCHEMA {db}.{s};' for s in all_schemas)
    infra = f"""\
-- ============================================================
-- Infrastructure: schemas managed by ADF
-- Generated by GENERATE_DCM_PROJECT
-- ============================================================

{schema_defs}
"""

    # ── tables.sql ────────────────────────────────────────────────────────────
    tables_lines = ["-- ============================================================",
                    "-- Silver layer tables — generated from ADF Executor output",
                    "-- ============================================================", ""]
    for schema, tbl in silver_tables:
        cols  = get_columns(schema, tbl)
        strat = strategies.get(tbl.upper(), {}).get('strategy', 'deduplicate')
        tables_lines.append(f"-- Strategy: {strat}")
        tables_lines.append(f"DEFINE TABLE {db}.{schema}.{tbl} (")
        defs  = [col_def(c) for c in cols]
        tables_lines.append(',\n'.join(defs))
        tables_lines.append(");\n")

    # ── analytics.sql ─────────────────────────────────────────────────────────
    analytics_lines = ["-- ============================================================",
                       "-- Gold / Analytics layer — generated from Analytics Builder",
                       "-- ============================================================", ""]
    for schema, tbl in gold_tables:
        cols  = get_columns(schema, tbl)
        col_list = ',\n'.join([col_def(c) for c in cols])
        analytics_lines.append(f"DEFINE TABLE {db}.{schema}.{tbl} (")
        analytics_lines.append(col_list)
        analytics_lines.append(");\n")

    # ── access.sql ────────────────────────────────────────────────────────────
    silver_grants = '\n'.join(
        f"GRANT USAGE ON SCHEMA {db}.{s} TO ROLE {data_engineer_role};\n"
        f"GRANT SELECT ON ALL TABLES IN SCHEMA {db}.{s} TO ROLE {data_engineer_role};"
        for s in silver_schemas
    )
    gold_grants = '\n'.join(
        f"GRANT USAGE ON SCHEMA {db}.{s} TO ROLE {analyst_role};\n"
        f"GRANT SELECT ON ALL TABLES IN SCHEMA {db}.{s} TO ROLE {analyst_role};"
        for s in gold_schemas
    )
    access = f"""\
-- ============================================================
-- Access control — generated by ADF
-- ============================================================

-- Silver / Enriched: data engineers can read
{silver_grants}

-- Gold / Analytics: analysts can read
{gold_grants}
"""

    # ── expectations.sql ─────────────────────────────────────────────────────
    exp_lines = ["-- ============================================================",
                 "-- Data quality expectations — NULL checks on PK columns",
                 "-- Source: Planner decisions (primary) / _ID heuristic (fallback)",
                 "-- ============================================================", ""]
    for schema, tbl in silver_tables:
        tbl_upper = tbl.upper()
        if tbl_upper in pk_map:
            pk_cols = pk_map[tbl_upper]
            source  = 'planner'
        else:
            cols    = get_columns(schema, tbl)
            pk_cols = [c[0] for c in cols if c[0].upper().endswith('_ID') and c[2] == 'NO']
            source  = 'heuristic'

        if pk_cols:
            exp_lines.append(f"-- {tbl} ({source}: {', '.join(pk_cols)})")
            for pk in pk_cols:
                exp_lines.append(f"ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT")
                exp_lines.append(f"    TO TABLE {db}.{schema}.{tbl}")
                exp_lines.append(f"    ON ({pk})")
                exp_lines.append(f"    EXPECTATION NO_NULLS (value = 0);\n")

    # ── Assemble file map ─────────────────────────────────────────────────────
    files = {
        'manifest.yml':                          manifest,
        'sources/definitions/infrastructure.sql': infra,
        'sources/definitions/tables.sql':         '\n'.join(tables_lines),
        'sources/definitions/analytics.sql':      '\n'.join(analytics_lines),
        'sources/definitions/access.sql':         access,
        'sources/definitions/expectations.sql':   '\n'.join(exp_lines),
    }

    # ── Write to stage ────────────────────────────────────────────────────────
    written = []
    with tempfile.TemporaryDirectory() as tmpdir:
        for rel_path, content in files.items():
            local_path = os.path.join(tmpdir, os.path.basename(rel_path))
            with open(local_path, 'w') as f:
                f.write(content)
            stage_dir = '@AGENT_FRAMEWORK.DCM_OUTPUT/' + '/'.join(rel_path.split('/')[:-1])
            stage_dir = stage_dir.rstrip('/')
            session.file.put(f'file://{local_path}', stage_dir + '/',
                             auto_compress=False, overwrite=True)
            written.append(rel_path)

    return {
        'status':         'SUCCESS',
        'project_name':   project_name,
        'files_written':  written,
        'silver_tables':  len(silver_tables),
        'gold_tables':    len(gold_tables),
        'silver_schemas': silver_schemas,
        'gold_schemas':   gold_schemas,
        'stage':          f'@AGENT_FRAMEWORK.DCM_OUTPUT',
        'contents':       files,
        'deploy_hint':    f'snow dcm deploy {db}.AGENT_FRAMEWORK.{project_name.upper()} --target DEV'
    }
$$;
